### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "d952fe63df0944c98646e24e62ddb040",
  "accountNumber": "1000000002",
  "amount": 20000
}

### query transaction
GET http://localhost:8080/transaction/22218e4fcada4f01899ff7eaedd1b9

d3